/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorForm.java
 *
 * Created on Jan 23, 2012, 10:50:15 AM
 */
package Presentation;
import Application.Employee;
import Application.Student;
import Application.Course;

import java.util.List;
import java.util.ListIterator;

/**
 *
 * @author lapowner
 */
public class EditorForm extends javax.swing.JDialog {
    
    String activetab = "";
    List<Employee> emplist; ListIterator<Employee> empiterator;
    List<Student> studlist; ListIterator<Student> studiterator; 
    List<Course> courselist; ListIterator<Course> courseiterator;

    /** Creates new form EditorForm */
    public EditorForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //display first employee record
        try{
            getList();
            //display employee list
            while(empiterator.hasPrevious()){
                  empiterator.previous();
            }
            Employee emp = empiterator.next();            
            DisplayEmpInfo(emp);
            
            //display student list
            while(studiterator.hasPrevious()){
                  studiterator.previous();
            }
            Student stud = studiterator.next();            
            DisplayStudInfo(stud);    
            //display course list
            while(courseiterator.hasPrevious()){
                  courseiterator.previous();
            }
            Course course = courseiterator.next();            
            DisplayCourseInfo(course);             
        }
        catch(Exception e){}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        BirthdateTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        GenderTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        GrandfatherTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FatherNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmpTypeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmpYearTextField = new javax.swing.JTextField();
        EmpIDLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        birthdate = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        grandFather = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        enrolYear = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        enrolType = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        StudIDLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CourseTitleTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CreditHourComboBox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LevelComboBox = new javax.swing.JComboBox();
        HostDeptTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        SemesterComboBox = new javax.swing.JComboBox();
        PrerequisiteTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        CourseIdLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        FirstLabel = new javax.swing.JLabel();
        PreviousLabel = new javax.swing.JLabel();
        LastLabel = new javax.swing.JLabel();
        NextLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Editor Form");

        TabbedPane.setName(""); // NOI18N
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneMouseClicked(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setText("Username:");

        jLabel8.setText("Date of Birth:");

        jLabel7.setText("Gender:");

        GenderTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Grand father:");

        jLabel5.setText("Father's name:");

        jLabel9.setText("Password:");

        jLabel3.setText("Employment Year:");
        jLabel3.setToolTipText("");

        jLabel2.setText("Emp Type:");
        jLabel2.setToolTipText("");

        jLabel4.setText("Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(EmpIDLabel)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordTextField)
                                    .addComponent(BirthdateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmpTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GrandfatherTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(FatherNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(EmpYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EmpTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FatherNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GrandfatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(EmpIDLabel))
        );

        TabbedPane.addTab("Employee", jPanel2);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel10.setText("Date of Birth:");

        jLabel11.setText("Password:");

        jLabel12.setText("Enrollment Type:");

        jLabel13.setText("Enrollment Year:");

        jLabel14.setText("Name:");

        jLabel15.setText("Gender:");

        jLabel16.setText("Grand father:");

        jLabel17.setText("Father's name:");

        jLabel18.setText("Username:");

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(StudIDLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enrolType, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(4, 4, 4))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrolYear, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(grandFather, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(birthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(fatherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(enrolType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(enrolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(grandFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(StudIDLabel))
        );

        TabbedPane.addTab("Student", jPanel1);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel19.setText("Title:");

        CreditHourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        CreditHourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditHourComboBoxActionPerformed(evt);
            }
        });

        jLabel20.setText("Credit hour:");

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel21.setText("Semester:");

        jLabel22.setText("Host Dept:");

        jLabel23.setText("Year:");

        LevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachelore", "Master", "Doctoroal" }));

        jLabel24.setText("Pre requisite:");

        SemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        jLabel25.setText("Level:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CourseTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LevelComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SemesterComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 97, Short.MAX_VALUE)
                                    .addComponent(YearComboBox, 0, 97, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CreditHourComboBox, 0, 141, Short.MAX_VALUE)
                                    .addComponent(HostDeptTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(PrerequisiteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(CourseIdLabel)
                        .addGap(99, 99, 99))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CourseTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostDeptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(LevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrerequisiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreditHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGap(47, 47, 47)
                .addComponent(CourseIdLabel)
                .addContainerGap())
        );

        TabbedPane.addTab("Course", jPanel3);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        FirstLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        FirstLabel.setForeground(new java.awt.Color(51, 51, 255));
        FirstLabel.setText("First");
        FirstLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FirstLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstLabelMouseClicked(evt);
            }
        });

        PreviousLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        PreviousLabel.setForeground(new java.awt.Color(51, 51, 255));
        PreviousLabel.setText("<<Previous");
        PreviousLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PreviousLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreviousLabelMouseClicked(evt);
            }
        });

        LastLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        LastLabel.setForeground(new java.awt.Color(51, 51, 255));
        LastLabel.setText("Last");
        LastLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LastLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastLabelMouseClicked(evt);
            }
        });

        NextLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        NextLabel.setForeground(new java.awt.Color(51, 51, 255));
        NextLabel.setText("Next>>");
        NextLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextLabelMouseClicked(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(FirstLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(PreviousLabel)
                        .addGap(18, 18, 18)
                        .addComponent(NextLabel)
                        .addGap(103, 103, 103)
                        .addComponent(LastLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(ClearButton)
                        .addGap(100, 100, 100)
                        .addComponent(CloseButton)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstLabel)
                    .addComponent(LastLabel)
                    .addComponent(NextLabel)
                    .addComponent(PreviousLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(CloseButton)
                    .addComponent(ClearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try{
            if(activetab.equals("Employee")||(activetab.equals(""))){
                  String birthdate = BirthdateTextField.getText();
                         birthdate = birthdate.substring(0, 4) + birthdate.substring(5,7)+birthdate.substring(8, 10);
                  String year = EmpYearTextField.getText().substring(0, 4);
                  Employee emp = new Employee(NameTextField.getText(), FatherNameTextField.getText(),
                          GrandfatherTextField.getText(),GenderTextField.getText(),birthdate, 
                          EmpTypeTextField.getText(), year,UsernameTextField.getText(),
                          PasswordTextField.getText(), "No");
                  emp.setID(Integer.parseInt(EmpIDLabel.getText()));
                  emp.Update(emp);
            }
            else if(activetab.equals("Student")||(activetab.equals(""))){
                  String bdate = birthdate.getText();
                         bdate = bdate.substring(0, 4) + bdate.substring(5,7)+bdate.substring(8, 10);
                  String year = enrolYear.getText().substring(0, 4);
                  Student stud = new Student(name.getText(), fatherName.getText(),
                                             grandFather.getText(),gender.getText(),birthdate.getText(), 
                                             enrolType.getText(), year,usernameText.getText(),
                                             passwordText.getText(), "No");
                  stud.setIDs(Integer.parseInt(StudIDLabel.getText()));                 
                  stud.Update(stud);
            }     
            else if(activetab.equals("Course")||(activetab.equals(""))){
                  String requisite = PrerequisiteTextField.getText();                
                  String credithr = CreditHourComboBox.getSelectedItem().toString();
                  String year = YearComboBox.getSelectedItem().toString();
                  String semester = SemesterComboBox.getSelectedItem().toString();
                  Course course = new Course(CourseTitleTextField.getText(), HostDeptTextField.getText(),
                                    LevelComboBox.getSelectedItem().toString(),requisite,credithr,year, semester);
                  course.setIDs(Integer.parseInt(CourseIdLabel.getText()));
                  course.Update(course);
            }                    
        } 
        catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void NextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextLabelMouseClicked
        
        try{
            if(activetab.equals("Employee")||(activetab.equals(""))){
                Employee emp = empiterator.next();
                DisplayEmpInfo(emp);
            }
            else if(activetab.equals("Student")){
                Student stud = studiterator.next();
                DisplayStudInfo(stud);
            }
            else if(activetab.equals("Course")){
                Course course = courseiterator.next();
                DisplayCourseInfo(course);
            }            
        }
        catch(Exception e) {}
    }//GEN-LAST:event_NextLabelMouseClicked
    
    private void PreviousLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousLabelMouseClicked
        
        try {   
             if(activetab.equals("Employee")||(activetab.equals(""))){
                 Employee emp = empiterator.previous();
                 DisplayEmpInfo(emp); 
             }
             else if(activetab.equals("Student")){
                Student stud = studiterator.previous();
                DisplayStudInfo(stud);             
             }
             else if(activetab.equals("Course")){
                Course course = courseiterator.previous();
                DisplayCourseInfo(course);             
             }             
        } 
        catch (Exception e) {}    
        
    }//GEN-LAST:event_PreviousLabelMouseClicked

    private void FirstLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstLabelMouseClicked
        
        try {      
             if(activetab.equals("Employee")||(activetab.equals(""))){            
                while (empiterator.hasPrevious())empiterator.previous();                          
                Employee emp = empiterator.next();             
                DisplayEmpInfo(emp);  
             }
             else if(activetab.equals("Student")){
                while (studiterator.hasPrevious())studiterator.previous();                          
                Student stud = studiterator.next();             
                DisplayStudInfo(stud);                   
             }
             else if(activetab.equals("Course")){
                while (courseiterator.hasPrevious())courseiterator.previous();                          
                Course course = courseiterator.next();             
                DisplayCourseInfo(course);                   
             }             
        } 
        catch (Exception e) {}     
        
    }//GEN-LAST:event_FirstLabelMouseClicked

    private void LastLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastLabelMouseClicked
        
        try {     
             if(activetab.equals("Employee")||(activetab.equals(""))){             
                while (empiterator.hasNext())empiterator.next();            
                Employee emp = empiterator.previous();             
                DisplayEmpInfo(emp);
             }
             else if(activetab.equals("Student")){
                while (studiterator.hasNext())studiterator.next();            
                Student stud = studiterator.previous();             
                DisplayStudInfo(stud);                 
             }      
             else if(activetab.equals("Course")){
                while (courseiterator.hasNext())courseiterator.next();            
                Course course = courseiterator.previous();             
                DisplayCourseInfo(course);                 
             } 
        } 
        catch (Exception e){}     

    }//GEN-LAST:event_LastLabelMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        if(activetab.equals("Employee")||(activetab.equals("")))         
            ClearEmpInfo();    
        else if(activetab.equals("Student"))
            ClearStudInfo();
        else if(activetab.equals("Course"))
            ClearCourseInfo();        
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void TabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMouseClicked

         activetab = TabbedPane.getAccessibleContext().getAccessibleName();     }//GEN-LAST:event_TabbedPaneMouseClicked

    private void CreditHourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditHourComboBoxActionPerformed

    }//GEN-LAST:event_CreditHourComboBoxActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed

    }//GEN-LAST:event_usernameTextActionPerformed
    private void getList() {
        //get employee list
        Employee emp = new Employee();
        emplist = emp.getEmployeeList(); 
        empiterator = emplist.listIterator( emplist.size() );    
        //get student list
        Student stud = new Student();
        studlist = stud.getStudentLinkedList(); 
        studiterator = studlist.listIterator( studlist.size() );
        //get course list
        Course course = new Course();
        courselist = course.getCourseList(); 
        courseiterator = courselist.listIterator( courselist.size() );        
    }
    private void DisplayEmpInfo(Employee emp){
        EmpIDLabel.setText(Integer.toString(emp.getId()));
        EmpIDLabel.setVisible(false);
        
        EmpTypeTextField.setText(emp.getEnrolType());
        EmpYearTextField.setText(emp.getEnrolYear());
        NameTextField.setText(emp.getName());
        FatherNameTextField.setText(emp.getFatherName());
        GrandfatherTextField.setText(emp.getGrandFather());
        GenderTextField.setText(emp.getGender());
        BirthdateTextField.setText(emp.getBirthdate());
        UsernameTextField.setText(emp.getUsername());
        PasswordTextField.setText(emp.getPassword());
        FirstLabel.setToolTipText("Click here");
        LastLabel.setToolTipText("Click here");
        PreviousLabel.setToolTipText("Click here");
        NextLabel.setToolTipText("Click here");        
    }
    private void DisplayStudInfo(Student stud){    
        StudIDLabel.setText(Integer.toString(stud.getId()));
        StudIDLabel.setVisible(false);       
        
        enrolType.setText(stud.getEnrolType()); 
        enrolYear.setText(stud.getEnrolYear()); 
        name.setText(stud.getName());
        fatherName.setText(stud.getFatherName()); 
        grandFather.setText(stud.getGrandFather()); 
        gender.setText(stud.getGender());
        birthdate.setText(stud.getBirthdate()); 
        usernameText.setText(stud.getUsername());
        passwordText.setText(stud.getPassword()); 
    }    
    private void DisplayCourseInfo(Course course){
        CourseIdLabel.setText(Integer.toString(course.getCourseId()));
        CourseIdLabel.setVisible(false);
        
        CourseTitleTextField.setText(course.getTitle());
        HostDeptTextField.setText(course.getHostDept());
        PrerequisiteTextField.setText(course.getRequisite());
        LevelComboBox.setSelectedItem(course.getLevel());
        YearComboBox.setSelectedItem(course.getYear());
        SemesterComboBox.setSelectedItem(course.getSemester());
        CreditHourComboBox.setSelectedItem(course.getCredithour());
    }
    private void ClearEmpInfo(){
        EmpTypeTextField.setText("");
        EmpYearTextField.setText("");
        NameTextField.setText("");
        FatherNameTextField.setText("");
        GrandfatherTextField.setText("");
        GenderTextField.setText("");
        BirthdateTextField.setText("");
        UsernameTextField.setText("");
        PasswordTextField.setText("");          
    }
    private void ClearStudInfo(){    
        enrolType.setText(""); 
        enrolYear.setText(""); 
        name.setText("");
        fatherName.setText(""); 
        grandFather.setText(""); 
        gender.setText("");
        birthdate.setText(""); 
        usernameText.setText("");
        passwordText.setText(""); 
    }
    private void ClearCourseInfo(){ 
        CourseTitleTextField.setText("");
        HostDeptTextField.setText("");
        PrerequisiteTextField.setText("");
        LevelComboBox.setSelectedIndex(0);        
        YearComboBox.setSelectedIndex(0);
        SemesterComboBox.setSelectedIndex(0);
        CreditHourComboBox.setSelectedIndex(0);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditorForm dialog = new EditorForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BirthdateTextField;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel CourseIdLabel;
    private javax.swing.JTextField CourseTitleTextField;
    private javax.swing.JComboBox CreditHourComboBox;
    private javax.swing.JLabel EmpIDLabel;
    private javax.swing.JTextField EmpTypeTextField;
    private javax.swing.JTextField EmpYearTextField;
    private javax.swing.JTextField FatherNameTextField;
    private javax.swing.JLabel FirstLabel;
    private javax.swing.JTextField GenderTextField;
    private javax.swing.JTextField GrandfatherTextField;
    private javax.swing.JTextField HostDeptTextField;
    private javax.swing.JLabel LastLabel;
    private javax.swing.JComboBox LevelComboBox;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NextLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField PrerequisiteTextField;
    private javax.swing.JLabel PreviousLabel;
    private javax.swing.JComboBox SemesterComboBox;
    private javax.swing.JLabel StudIDLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JComboBox YearComboBox;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField enrolType;
    private javax.swing.JTextField enrolYear;
    private javax.swing.JTextField fatherName;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField grandFather;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
